name: Prepare-PR

on:
 workflow_dispatch:
  inputs:
   logLevel:
     description: 'Log level'     
     required: true
     default: 'warning'
   tags:
     description: 'Test scenario tags'  

jobs:
 updating_from_main:
  runs-on: ubuntu-latest
         
  steps:
   - name: Preparing the PR
     run: |
      git clone --branch=RetroDECK --recursive https://github.com/XargonWan/flathub.git
      git clone --recursive https://github.com/XargonWan/RetroDECK.git
      cd RetroDECK
      git submodule init
      git submodule update
      cd ..
      mv -f RetroDECK/* flathub/
      rm -rf RetroDECK
      cd flathub
      git submodule init
      git submodule update
      git add *
      git commit -m "Updating flathub"
      git push origin RetroDECK
